# need openjdk
From openjdk
#work directory
WORKDIR usr/lib


#jars
ADD ./target/gateway-0.0.1-SNAPSHOT.jar /usr/lib/gateway-0.0.1-SNAPSHOT.jar

# add starting jars when containerstart
ENTRYPOINT ["java","-jar","gateway-0.0.1-SNAPSHOT.jar"]